spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 010518
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
  jpa:
    hibernate:
      # 更新数据表
      ddl-auto: update
    # 控制台显示sql
    show-sql: true

